@startuml

loop forever

    activate Thread1
    Thread1 -> Thread1 : do work for 2-4
    activate Thread1
    deactivate Thread1
    Thread1 -> Lock1 : Acquire
    activate Lock1
    Thread1 -> Thread1 : do work for 4-6
    activate Thread1
    deactivate Thread1
    Thread1 -> Lock2 : Acquire
    activate Lock2
    Thread1 -> Thread1 : sleep for 4
    activate Thread1
    deactivate Thread1
    Thread1 <-- Lock1 : Release
    deactivate Lock1
    Thread1 <-- Lock2 : Release
    deactivate Lock2
    Thread1 -> Thread1 : Wait for Thread2
    activate Thread1
    deactivate Thread1

    activate Thread2
    Thread2 -> Thread2 : do work for 3-5
    activate Thread2
    deactivate Thread2
    Thread2 -> Lock2 : Acquire
    activate Lock2
    Thread2 -> Thread2 : do work for 5-7
    activate Thread2
    deactivate Thread2
    Thread2 -> Lock1 : Acquire
    activate Lock1
    Thread2 -> Thread2 : sleep for 5
    activate Thread2
    deactivate Thread2
    Thread2 <-- Lock2 : Release
    deactivate Lock2
    Thread2 <-- Lock1 : Release
    deactivate Lock1
    Thread2 -> Thread2 : Wait for Thread1
    activate Thread2
    deactivate Thread2

end loop

@enduml